# Generated by Django 5.0.4 on 2024-05-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JellybeanFlavors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=30)),
                ('s3_url', models.CharField(max_length=50)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
