# Generated by Django 5.0.4 on 2024-05-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0002_rename_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jellybeanflavor',
            name='s3_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
