# Generated by Django 5.0.4 on 2024-05-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0003_alter_jellybeanflavor_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jellybeanflavor',
            name='s3_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
