# Generated by Django 5.0.4 on 2024-05-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0004_alter_jellybeanflavor_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jellybeanflavor',
            name='s3_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
