# Generated by Django 5.0.4 on 2024-05-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0005_alter_jellybeanflavor_s3_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jellybeanflavor',
            old_name='s3_url',
            new_name='s3_image',
        ),
    ]
