# Generated by Django 5.0.4 on 2024-05-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0006_rename_s3_url_jellybeanflavor_s3_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jellybeanflavor',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
